### ISSUE TITLE
crash in settc

### ISSUE THREAD

**Issue by Rescator7** [MichaelB7/Crafty#11]
unable to open book file [./book.bin].
book is disabled
unable to open book file [./books.bin].

Crafty v25.6

machine has 8 processors

White(1): settc 0 5 0 5
time remaining:   5:00 (white).
time remaining:   5:00 (black).
0 moves to next time control (white)
0 moves to next time control (black)
Floating point exception (core dumped)

**Comment by MichaelB7** [comment]
`usage:  settc <wmoves> <wtime> <bmoves> <btime>`

You can not use zero, it's a division by zero error.
