### ISSUE TITLE
Fedora 25 - compiled with unix-gcc | execution failed (Illegal operation (core dumped))

### ISSUE THREAD

**Issue by neunzehnachtneun** [MichaelB7/Crafty#2]
Hey,
I have some problems getting Crafty running.
I compiled it on two different machines, one with opensuse (kernel 4.4.36-8-default, gcc 4.8.5), one with Fedora 25 (kernel 4.9.5-200, gcc 6.3.1).

I compiled with
make unix-gcc
and 
make unix-gcc-profile

Both versions are working with opensuse but not with Fedora.
The error is quite short after:
./crafty
Illegal instruction (core dumped)

Do you know how to deal with this?

Kind, 
Sebastian

**Comment by toneewa** [comment]
Usually, that means your program is compiled with optimizations that are not supported.

Try to install 
sudo apt-get install cmake

**Comment by MichaelB7** [comment]
This one is stale - closing .  Please reopen if still you have an issue.
