### ISSUE TITLE
Crafty 25.3 Compiling with Visual Studio 2013/2015/2017 on Windows 7

### ISSUE THREAD

**Issue by DrOfIllusions** [MichaelB7/Crafty#3]
When I try to use Visual Studio to compile Crafty 25.3 on a windows machine I get the following errors, any advice on how to address these issues in bulk rather than fix them manually or is this my only option? Thanks!

Error	3	error C4996: 'isatty': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _isatty. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\utility.c	275	1	Crafty25_3
Error	32	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\thread.c	793	1	Crafty25_3
Error	38	error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\test.c	54	1	Crafty25_3
Error	39	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	40	error C2085: 'tb_init' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	41	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	42	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	193	1	Crafty25_3
Error	43	error C2085: 'tb_probe_wdl' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	44	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	45	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	251	1	Crafty25_3
Error	46	error C2085: 'tb_probe_root' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	47	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	48	error C1083: Cannot open include file: 'unistd.h': No such file or directory	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbcore.c	11	1	Crafty25_3
Error	49	error C1083: Cannot open include file: 'unistd.h': No such file or directory	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbcore.c	11	1	Crafty25_3
Error	50	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\setboard.c	63	1	Crafty25_3
Error	51	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\see.c	81	1	Crafty25_3
Error	52	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\see.c	152	1	Crafty25_3
Error	53	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\see.c	180	1	Crafty25_3
Error	54	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\resign.c	112	1	Crafty25_3
Error	55	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\ponder.c	52	1	Crafty25_3
Error	56	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\output.c	30	1	Crafty25_3
Error	57	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	58	error C2085: 'tb_init' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	59	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	60	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	193	1	Crafty25_3
Error	61	error C2085: 'tb_probe_wdl' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	62	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	63	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	251	1	Crafty25_3
Error	64	error C2085: 'tb_probe_root' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	65	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	89	error C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\next.c	452	1	Crafty25_3
Error	92	error C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\main.c	4274	1	Crafty25_3
Error	94	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	95	error C2085: 'tb_init' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	96	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	97	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	193	1	Crafty25_3
Error	98	error C2085: 'tb_probe_wdl' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	99	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	100	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	251	1	Crafty25_3
Error	101	error C2085: 'tb_probe_root' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	102	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	114	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\input.c	71	1	Crafty25_3
Error	115	error C4996: '_fmode': This function or variable may be unsafe. Consider using _get_fmode instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\init.c	38	1	Crafty25_3
Error	117	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\init.c	417	1	Crafty25_3
Error	119	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\init.c	450	1	Crafty25_3
Error	131	error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\evtest.c	48	1	Crafty25_3
Error	132	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	133	error C2085: 'tb_init' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	134	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	167	1	Crafty25_3
Error	135	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	193	1	Crafty25_3
Error	136	error C2085: 'tb_probe_wdl' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	137	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	197	1	Crafty25_3
Error	138	error C2054: expected '(' to follow 'inline'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	251	1	Crafty25_3
Error	139	error C2085: 'tb_probe_root' : not in formal parameter list	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	140	error C2143: syntax error : missing ';' before '{'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbprobe.h	254	1	Crafty25_3
Error	174	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\see.c	81	1	Crafty25_3
Error	175	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\see.c	152	1	Crafty25_3
Error	176	error C4146: unary minus operator applied to unsigned type, result still unsigned	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\see.c	180	1	Crafty25_3
Error	192	error C1083: Cannot open include file: 'unistd.h': No such file or directory	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\tbcore.c	11	1	Crafty25_3
Error	193	error C2059: syntax error : 'constant'	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\boolean.c	19	1	Crafty25_3
Error	202	error C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\book.c	470	1	Crafty25_3
Error	215	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\bench.c	124	1	Crafty25_3
Error	218	error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\autotune.c	50	1	Crafty25_3
Error	222	error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\annotate.c	103	1	Crafty25_3
Error	225	error C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\AllUsers\desktop\crafty 25.3\visual studio project\crafty25_3\source_original\analyze.c	119	1	Crafty25_3
	226	IntelliSense: cannot open source file "unistd.h"	c:\Users\AllUsers\Desktop\Crafty 25.3\Visual Studio Project\Crafty25_3\Source_Original\tbcore.c	11	1	Crafty25_3
	227	IntelliSense: cannot open source file "sys/mman.h"	c:\Users\AllUsers\Desktop\Crafty 25.3\Visual Studio Project\Crafty25_3\Source_Original\tbcore.c	18	1	Crafty25_3
	228	IntelliSense: identifier "pthread_mutex_t" is undefined	c:\Users\AllUsers\Desktop\Crafty 25.3\Visual Studio Project\Crafty25_3\Source_Original\tbcore.c	42	8	Crafty25_3
	229	IntelliSense: cannot open source file "pthread.h"	c:\Users\AllUsers\Desktop\Crafty 25.3\Visual Studio Project\Crafty25_3\Source_Original\tbcore.h	9	1	Crafty25_3
	230	IntelliSense: expected a type specifier	c:\Users\AllUsers\Desktop\Crafty 25.3\Visual Studio Project\Crafty25_3\Source_Original\tbcore.h	87	18	Crafty25_3

**Comment by MichaelB7** [comment]
Sorry I'm not a windows user , I have a friend on vacation and will ask him to take a look when he gets back .  Will take a few weeks. Thanks.

**Comment by mymoso** [comment]
Please Mr. Michael

I need a win 64x popcnt of this engine. Can you help?

**Comment by 0xrgb** [comment]
@mymoso you could use `__popcnt` functions.
You need to include `intrin.h`. (See [MSDN](https://msdn.microsoft.com/en-US/library/bb385231.aspx))

**Comment by MichaelB7** [comment]
Checkout this branch where we are collecting changes to make it easier for Windows

https://github.com/MichaelB7/Crafty/tree/09182019

Proposed changes to date:

https://github.com/MichaelB7/Crafty/pull/8/files

**Comment by MichaelB7** [comment]
Any new comments/questions for compiling under Windows should be noted here (until this PR is closed).

https://github.com/MichaelB7/Crafty/pull/8

I'm not on Windows,. so if there are any experts on compiling for Windows out there, please feel free to chime in.
