### ISSUE TITLE
Compilation w/o popcount?

### ISSUE THREAD

**Issue by rwbc** [MichaelB7/Crafty#7]
Would you mind to compile a version of the new 25.3 w/o popcount for older 64-bit hardware?
Thanks.

**Comment by toneewa** [comment]
Try this one: https://www.mediafire.com/file/5qvoehqo8asn2ub/crafty.zip/file

**Comment by MichaelB7** [comment]
25.2 and 25.3 and all changes made so far are the exact same engine functionality.    If 25.2 is working , no need to upgrade to 25.3

I cannot accept links to 3rd party website when I cannnot vouch for what is in the zip file ,  I have to delete it,  Sorry.
